import os
import pandas as pd


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PREDICTIONS_FILE = os.path.join(
    BASE_DIR,
    "herd_predictions.csv"
)

_cached_df = None
_cached_mtime = 0.0


def load_predictions():
    """
    Load the latest herd predictions generated by mastitis_pipeline.py.
    Uses timestamp caching to prevent redundant disk I/O.
    """
    global _cached_df, _cached_mtime

    if not os.path.exists(PREDICTIONS_FILE):
        raise FileNotFoundError(
            f"Prediction file not found: {PREDICTIONS_FILE}"
        )

    mtime = os.path.getmtime(PREDICTIONS_FILE)

    if _cached_df is None or mtime > _cached_mtime:
        _cached_df = pd.read_csv(PREDICTIONS_FILE)
        _cached_mtime = mtime

    return _cached_df


def get_cow(cow_id):
    """
    Return prediction data for one cow.
    """

    df = load_predictions()

    result = df[df["cow_id"].astype(str) == str(cow_id)]

    if result.empty:
        return None

    return result.iloc[0].to_dict()


def get_all_cows():
    """
    Return all cow predictions.
    """

    df = load_predictions()

    return df.to_dict(orient="records")